# Generated by Django 4.0.2 on 2022-03-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=60)),
                ('head0', models.CharField(max_length=60)),
                ('chead0', models.CharField(max_length=500)),
                ('head1', models.CharField(max_length=60)),
                ('chead1', models.CharField(max_length=500)),
                ('head2', models.CharField(max_length=60)),
                ('chead2', models.CharField(max_length=500)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='buybest/images')),
            ],
        ),
    ]
