# Generated by Django 4.0.2 on 2022-03-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpost_chead0_alter_blogpost_chead1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='posted_by',
            field=models.CharField(default='Admin', max_length=25),
        ),
    ]
