# Generated by Django 4.0.2 on 2022-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_by',
            field=models.CharField(max_length=25),
        ),
    ]
